#!/usr/bin/env bash
cp $1_samples.cpp instrument_samples.cpp
cp $1_samples.h instrument_samples.h

grep "uint32_t sample_" instrument_samples.cpp|cut -d\[ -f2| cut -d\] -f1 >sizes
count=`wc -l sizes|cut -d' ' -f1`
echo "" >>instrument_samples.cpp
echo "std::vector<uint16_t> sizes_array {" >>instrument_samples.cpp
for i in `cat sizes`
do
echo "$i, " >>instrument_samples.cpp
done
echo "};" >>instrument_samples.cpp
# The following sed script does this in order
# 1. Changes the include file name.
# 2. Globally removes al references to AudioSynthWavetable
# 3. Globally remove all const keywords.
# 4. Globally remove all PROGMEM keywords.
# 5. Globally remove all int16_t* pointer coercions.
# 6. Globally change all references to the original instrument name prefix
#    to "instrument".
# 7. Change the intrument_ranges type to std::vector<uint8_t>.
# 8. Change the intrument metadata array to std::vector<sample_data>.
sed -i -e "/^#include/s/$1/instrument/g;
            s/AudioSynthWavetable:://g;
            s/const//g;
            s/PROGMEM//g;
            s/(int16_t\*)sample_/sample_/g;
            s/$1/instrument/g;
            s/static  uint8_t instrument_ranges\[\] =/std::vector<uint8_t> instrument_ranges/g;
            s/static  sample_data instrument_samples\[$count\] =/std::vector<sample_data> instrument_samples/g;
            s/static   uint32_t sample_/std::vector<uint32_t> sample_/g;
            /^std::vector<uint32_t>/s/\[.*\]//" instrument_samples.cpp
sed -i -e 's/^#include <Audio.h>/#include <vector>/g;
            s/AudioSynthWavetable:://g' instrument_samples.h
rm sizes
